import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const poppins = Poppins({
  weight: ["500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Voice Interview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <ClerkProvider>
        {/* ออกแบบ layout  */}
        <body
          className={cn(
            `${poppins.className} antialiased min-h-screen bg-background`,
          )}
        >
          {/* จัด layout nav+footer */}
          <div className="relative flex min-h-screen flex-col">
            <Navbar />
            <main className="flex-1 w-full mx-auto px-4 max-w-7xl sm:px-6 lg:px-8 py-8">
              {children}
            </main>
            <Footer />
          </div>
        </body>
      </ClerkProvider>
    </html>
  );
}
